# Generated by Django 2.2.3 on 2019-07-16 09:08

from django.db import migrations, models
import django.db.models.deletion
import bitrix24_bridge.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0016_auto_20190327_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSectionBX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.IntegerField(blank=True, null=True, verbose_name='Section ID')),
                ('name', models.CharField(max_length=256, verbose_name='Section name')),
                ('catalog_id', models.IntegerField(blank=True, null=True, verbose_name='Catalog ID')),
                ('section_id', models.IntegerField(blank=True, null=True, verbose_name='Associated section ID')),
                ('xml_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mnemonic code')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
            bases=(models.Model, bitrix24_bridge.mixin.BitrixSyncMixin),
        ),
    ]
