# Generated by Django 2.2.3 on 2019-07-17 13:25

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import bitrix24_bridge.mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0016_auto_20190327_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSectionBX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Section ID')),
                ('name', models.CharField(max_length=256, verbose_name='Section name')),
                ('catalog_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Catalog ID')),
                ('section_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Associated section ID')),
                ('xml_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mnemonic code')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category')),
            ],
            bases=(models.Model, bitrix24_bridge.mixin.BitrixSyncMixin),
        ),
        migrations.CreateModel(
            name='ProductPropertyBX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=256, verbose_name='Product name')),
                ('iblock_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='IBlock id')),
                ('active', models.CharField(blank=True, default='Y', max_length=64, null=True, verbose_name='Active')),
                ('sort', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sort')),
                ('default_value', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True, verbose_name='Default Value')),
                ('property_type', models.CharField(max_length=64, verbose_name='Property ype')),
                ('row_count', models.CharField(blank=True, default=1, max_length=128, null=True, verbose_name='Row count')),
                ('col_count', models.CharField(blank=True, max_length=128, null=True, verbose_name='Col count')),
                ('multiple', models.CharField(blank=True, default='N', max_length=64, null=True, verbose_name='Multiple')),
                ('xml_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mnemonic code')),
                ('file_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='File type')),
                ('link_iblock_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Link iblock id')),
                ('is_required', models.CharField(blank=True, default='N', max_length=256, null=True, verbose_name='Is required')),
                ('user_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='User Type')),
                ('user_type_settings', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True, verbose_name='User Type settings')),
                ('values', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True, verbose_name='Values')),
                ('product_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.ProductAttribute')),
            ],
            bases=(models.Model, bitrix24_bridge.mixin.BitrixSyncMixin),
        ),
        migrations.CreateModel(
            name='ProductBX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitrix_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Product ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Product name')),
                ('active', models.CharField(blank=True, default='Y', max_length=16, null=True, verbose_name='Active')),
                ('sort', models.CharField(blank=True, max_length=128, null=True, verbose_name='Sort')),
                ('xml_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='Mnemonic code')),
                ('timestamp_x', models.CharField(blank=True, max_length=64, null=True, verbose_name='TIMESTAMP_X')),
                ('date_create', models.CharField(blank=True, max_length=64, null=True, verbose_name='DATE_CREATE')),
                ('catalog_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Catalog ID')),
                ('section_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Associated section ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_type', models.CharField(blank=True, default='text', max_length=64, null=True, verbose_name='Description type')),
                ('price', models.CharField(blank=True, max_length=256, null=True, verbose_name='Price')),
                ('currency_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Currency id')),
                ('vat_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Vat id')),
                ('vat_included', models.CharField(blank=True, max_length=64, null=True, verbose_name='Vat included')),
                ('measure', models.CharField(blank=True, max_length=256, null=True, verbose_name='Measure')),
                ('properties', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict, null=True, verbose_name='Custom properties')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product')),
            ],
            bases=(models.Model, bitrix24_bridge.mixin.BitrixSyncMixin),
        ),
    ]
