# Generated by Django 2.2.3 on 2019-07-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpropertybx',
            name='default_value',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Default Value'),
        ),
    ]
